// Mocks generated by Mockito 5.4.0 from annotations
// in mama_resto/test/restaurant_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mama_resto/features/restaurant/data/models/restaurant.dart'
    as _i6;
import 'package:mama_resto/features/restaurant/domain/entities/get_list_restaurant_params.dart'
    as _i7;
import 'package:mama_resto/features/restaurant/domain/repositories/restaurant_repository.dart'
    as _i2;
import 'package:mama_resto/features/restaurant/domain/usecases/get_list_restaurant.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRestaurantRepository_0 extends _i1.SmartFake
    implements _i2.RestaurantRepository {
  _FakeRestaurantRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetListRestaurant].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListRestaurant extends _i1.Mock implements _i4.GetListRestaurant {
  MockGetListRestaurant() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RestaurantRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRestaurantRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.RestaurantRepository);
  @override
  _i5.Future<_i3.Either<String, List<_i6.Restaurant>>> call(
          _i7.GetListRestaurantParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<String, List<_i6.Restaurant>>>.value(
            _FakeEither_1<String, List<_i6.Restaurant>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<String, List<_i6.Restaurant>>>);
}
